### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by farchanakbar** [rzkfyn/otakudesu-scraper#10]
bang, api nya sudah tidak bisa di akses lagi

**Comment by rzkfyn** [comment]
@farchanakbar buat sekarang pake domain dari vercel dulu ya. [otakudesu-unofficial-api.vercel.app](https://otakudesu-unofficial-api.vercel.app/)

**Comment by farchanakbar** [comment]
makasih bang hehe, sehat selalu
