### ISSUE TITLE
 "status": "Error",

### ISSUE THREAD

**Issue by KEVINGILBERTTODING** [rzkfyn/otakudesu-scraper#7]
{
  "status": "Error",
  "message": "Internal server error ;_;. If the error still persists in the next 1 hour, would appreciate if you kindly tell me. github.com/rzkfyn/otakudesu-scraper"
}

**Comment by rzkfyn** [comment]
semua endpoint kah?

**Comment by KEVINGILBERTTODING** [comment]
Iya bang semua Sent from Mail for Windows From: Rizki SofyanSent: Tuesday, January 16, 2024 6:01 PMTo: rzkfyn/otakudesu-scraperCc: Kevin Gilbert Toding; AuthorSubject: Re: [rzkfyn/otakudesu-scraper] "status": "Error", (Issue #7) semua endpoint kah?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by rzkfyn** [comment]
boleh di cek lagi ya, udah normal sekarang

**Comment by KEVINGILBERTTODING** [comment]
Baik bang, makasi Sent from Mail for Windows From: Rizki SofyanSent: Tuesday, January 16, 2024 7:47 PMTo: rzkfyn/otakudesu-scraperCc: Kevin Gilbert Toding; AuthorSubject: Re: [rzkfyn/otakudesu-scraper] "status": "Error", (Issue #7) boleh di cek lagi ya, udah normal sekarang—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
